micronaut.application.name = 'authService'
mongodb.uri = 'mongodb://root:password@localhost:27017/authService?authSource=admin'

[micronaut.jms.activemq.artemis]
enabled = true
connection-string = 'tcp://localhost:61616'

[micronaut.security]
authentication = 'bearer'
token.jwt.signatures.secret.generator.secret = 'pleaseChangeThisSecretForANewOne'
